import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "veranda_greenline" ALTER COLUMN "intro_text" SET DEFAULT 'De Greenline bewijst dat een hoogwaardige aluminium veranda niet duur hoeft te zijn. Door het slimme profielontwerp is er minder materiaal nodig terwijl de constructie zeer stevig blijft, met een verstevigde goot zijn zelfs overspanningen tot 7 meter op twee staanders mogelijk. De krasvaste Qualicoat-structuurlak is onderhoudsvriendelijk en milieubewust geproduceerd.';
  ALTER TABLE "veranda_profiline" ALTER COLUMN "hero_text" SET DEFAULT 'Onze meest veelzijdige veranda. Dankzij de extra stevige constructie bouwt u breder, dieper en ruimer, met overspanningen tot 7 meter op slechts twee staanders. Volledig op maat en uit te bouwen tot een complete tuinkamer.';
  ALTER TABLE "veranda_profiline" ALTER COLUMN "maat_text" SET DEFAULT 'Van afmeting, kleur en gootsierlijst tot geïntegreerde verlichting, verwarming, zonwering en glazen schuifwanden: de Profiline groeit mee met uw wensen.';
  ALTER TABLE "veranda_linea" ALTER COLUMN "intro_text" SET DEFAULT 'De Linea combineert strakke lijnen met een optisch vlak dak en een moderne uitstraling. Waar de Cube volledig kubistisch en robuust is, houdt de Linea een rankere, lichtere lijn aan. De overkapping sluit perfect aan bij een moderne bouwstijl en behoudt het buitengevoel, zowel aan de gevel als vrijstaand in de tuin.';
  ALTER TABLE "veranda_cube" ALTER COLUMN "intro_text" SET DEFAULT 'De Cube valt direct op met zijn strakke lijnen, extra brede staanders en volledig vlakke dak met onzichtbare dakhelling. Modern, robuust en tot in de puntjes afgewerkt, en dankzij een verstevigde goot mogelijk tot 7 meter breed op slechts twee palen. Een designstatement dat past bij een eigentijdse tuin, en heerlijk om onder te leven.';
  ALTER TABLE "tuinkamers" ALTER COLUMN "types_intro" SET DEFAULT 'De dakvorm bepaalt de uitstraling van uw tuinkamer. Een hellend dak en een vlak dak geven allebei een ander karakter. Wij zetten de verschillen voor u op een rij.';
  ALTER TABLE "tuinkamer_vlak_dak" ALTER COLUMN "intro_text" SET DEFAULT 'Het vlakke dak zorgt voor een minimalistisch silhouet met rechte lijnen en, bij de Cube, volledig verborgen afwatering. Gebaseerd op de Linea of Cube maakt u er een designstatement van dat naadloos aansluit op moderne architectuur, het hele jaar door te gebruiken.';
  ALTER TABLE "schuifwand_lamellen" ALTER COLUMN "hero_text" SET DEFAULT 'Verstelbare lamellen voor schaduw, privacy en ventilatie. Zet ze open voor frisse lucht en licht, of dicht voor beschutting. U regelt het zelf.';
  ALTER TABLE "schuifwand_steellook" ALTER COLUMN "intro_text" SET DEFAULT 'Steellook schuifwanden geven uw tuinkamer een stoere, industriële uitstraling met de warme charme van klassieke stalen puien, maar dan onderhoudsarm in aluminium. De slanke profielverdeling maakt er een echte blikvanger van.';
  ALTER TABLE "zonwering_uitvalschermen" ALTER COLUMN "hero_text" SET DEFAULT 'Compacte schermen die schuin naar buiten uitvallen en zo schaduw geven voor ramen en gevels, ook op de verdieping. Strak weggewerkt in een cassette.';
  ALTER TABLE "optie_wanden" ALTER COLUMN "intro_text" SET DEFAULT 'Met de juiste voor- en zijwandensluit u uw veranda helemaal af. Combineer glazen schuifwanden met kozijnen, deuren en ramen tot precies de indeling die bij uw situatie past. Het hele jaar door comfortabel.';
  ALTER TABLE "optie_dakbedekking" ALTER COLUMN "hero_text" SET DEFAULT 'Kies de dakbedekking die past bij uw wensen: van helder, warmtewerend of opaal polycarbonaat tot gelaagd veiligheidsglas, elk met een eigen lichtbeleving.';
  ALTER TABLE "optie_ledverlichting" ALTER COLUMN "hero_text" SET DEFAULT 'Sfeervolle, dimbare led-spots geïntegreerd in het dak van uw veranda. Energiezuinig en te bedienen op afstand, voor gezellige avonden buiten.';
  ALTER TABLE "optie_onderhoud" ALTER COLUMN "hero_text" SET DEFAULT 'Houd uw veranda jarenlang mooi met de juiste onderhoudsproducten. Speciaal voor aluminium, glas en polycarbonaat: onderhoudsarm, maar niet onderhoudsvrij.';
  ALTER TABLE "home" ADD COLUMN IF NOT EXISTS "welkom_bij_verandazeeland_tekst" jsonb;
  ALTER TABLE "home" DROP COLUMN IF EXISTS "welcome_text1";
  ALTER TABLE "home" DROP COLUMN IF EXISTS "welcome_text2";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "veranda_greenline" ALTER COLUMN "intro_text" SET DEFAULT 'De Greenline bewijst dat een hoogwaardige aluminium veranda niet duur hoeft te zijn. Door het slimme profielontwerp is er minder materiaal nodig terwijl de constructie zeer stevig blijft — met een verstevigde goot zijn zelfs overspanningen tot 7 meter op twee staanders mogelijk. De krasvaste Qualicoat-structuurlak is onderhoudsvriendelijk en milieubewust geproduceerd.';
  ALTER TABLE "veranda_profiline" ALTER COLUMN "hero_text" SET DEFAULT 'Onze meest veelzijdige veranda. Dankzij de extra stevige constructie bouwt u breder, dieper en ruimer — met overspanningen tot 7 meter op slechts twee staanders. Volledig op maat en uit te bouwen tot een complete tuinkamer.';
  ALTER TABLE "veranda_profiline" ALTER COLUMN "maat_text" SET DEFAULT 'Van afmeting, kleur en gootsierlijst tot geïntegreerde verlichting, verwarming, zonwering en glazen schuifwanden — de Profiline groeit mee met uw wensen.';
  ALTER TABLE "veranda_linea" ALTER COLUMN "intro_text" SET DEFAULT 'De Linea combineert strakke lijnen met een optisch vlak dak en een moderne uitstraling. Waar de Cube volledig kubistisch en robuust is, houdt de Linea een rankere, lichtere lijn aan. De overkapping sluit perfect aan bij een moderne bouwstijl en behoudt het buitengevoel — zowel aan de gevel als vrijstaand in de tuin.';
  ALTER TABLE "veranda_cube" ALTER COLUMN "intro_text" SET DEFAULT 'De Cube valt direct op met zijn strakke lijnen, extra brede staanders en volledig vlakke dak met onzichtbare dakhelling. Modern, robuust en tot in de puntjes afgewerkt — en dankzij een verstevigde goot mogelijk tot 7 meter breed op slechts twee palen. Een designstatement dat past bij een eigentijdse tuin, en heerlijk om onder te leven.';
  ALTER TABLE "tuinkamers" ALTER COLUMN "types_intro" SET DEFAULT 'De dakvorm bepaalt de uitstraling van uw tuinkamer. Een hellend dak en een vlak dak geven allebei een ander karakter — wij zetten de verschillen voor u op een rij.';
  ALTER TABLE "tuinkamer_vlak_dak" ALTER COLUMN "intro_text" SET DEFAULT 'Het vlakke dak zorgt voor een minimalistisch silhouet met rechte lijnen en, bij de Cube, volledig verborgen afwatering. Gebaseerd op de Linea of Cube maakt u er een designstatement van dat naadloos aansluit op moderne architectuur — het hele jaar door te gebruiken.';
  ALTER TABLE "schuifwand_lamellen" ALTER COLUMN "hero_text" SET DEFAULT 'Verstelbare lamellen voor schaduw, privacy en ventilatie. Zet ze open voor frisse lucht en licht, of dicht voor beschutting — u regelt het zelf.';
  ALTER TABLE "schuifwand_steellook" ALTER COLUMN "intro_text" SET DEFAULT 'Steellook schuifwanden geven uw tuinkamer een stoere, industriële uitstraling met de warme charme van klassieke stalen puien — maar dan onderhoudsarm in aluminium. De slanke profielverdeling maakt er een echte blikvanger van.';
  ALTER TABLE "zonwering_uitvalschermen" ALTER COLUMN "hero_text" SET DEFAULT 'Compacte schermen die schuin naar buiten uitvallen en zo schaduw geven voor ramen en gevels — ook op de verdieping. Strak weggewerkt in een cassette.';
  ALTER TABLE "optie_wanden" ALTER COLUMN "intro_text" SET DEFAULT 'Met de juiste voor- en zijwandensluit u uw veranda helemaal af. Combineer glazen schuifwanden met kozijnen, deuren en ramen tot precies de indeling die bij uw situatie past — het hele jaar door comfortabel.';
  ALTER TABLE "optie_dakbedekking" ALTER COLUMN "hero_text" SET DEFAULT 'Kies de dakbedekking die past bij uw wensen: van helder, warmtewerend of opaal polycarbonaat tot gelaagd veiligheidsglas — elk met een eigen lichtbeleving.';
  ALTER TABLE "optie_ledverlichting" ALTER COLUMN "hero_text" SET DEFAULT 'Sfeervolle, dimbare led-spots geïntegreerd in het dak van uw veranda. Energiezuinig en te bedienen op afstand — voor gezellige avonden buiten.';
  ALTER TABLE "optie_onderhoud" ALTER COLUMN "hero_text" SET DEFAULT 'Houd uw veranda jarenlang mooi met de juiste onderhoudsproducten. Speciaal voor aluminium, glas en polycarbonaat — onderhoudsarm, maar niet onderhoudsvrij.';
  ALTER TABLE "home" ADD COLUMN IF NOT EXISTS "welcome_text1" varchar DEFAULT 'Als officieel Verasol-dealer leveren wij de complete lijn hoogwaardige aluminium veranda''s: van de voordelige Greenline tot de exclusieve Cube. In Duitsland geproduceerd, betaalbaar en van perfecte kwaliteit. Een veranda kan zelfs worden omgebouwd naar een volwaardige tuinkamer voor nog meer woonplezier.';
  ALTER TABLE "home" ADD COLUMN IF NOT EXISTS "welcome_text2" varchar DEFAULT 'Kom langs voor deskundig en vrijblijvend advies aan De Stekelweie 2 te Serooskerke.';
  ALTER TABLE "home" DROP COLUMN IF EXISTS "welkom_bij_verandazeeland_tekst";`)
}
